/* Add real IDs below before enabling measurement. Leave blank to keep tracking disabled. */
const AGGLINK_TRACKING={ga4MeasurementId:'',googleAdsId:'',quoteConversionLabel:'',phoneConversionLabel:''};
const consentKey='agglink_cookie_consent';window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}
gtag('consent','default',{ad_storage:'denied',analytics_storage:'denied',ad_user_data:'denied',ad_personalization:'denied',wait_for_update:500});
function configured(){return /^G-[A-Z0-9]+$/.test(AGGLINK_TRACKING.ga4MeasurementId)||/^AW-[0-9]+$/.test(AGGLINK_TRACKING.googleAdsId)}
function loadGoogle(){if(!configured()||document.querySelector('script[data-google-tag]'))return;const id=AGGLINK_TRACKING.ga4MeasurementId||AGGLINK_TRACKING.googleAdsId;const s=document.createElement('script');s.async=true;s.dataset.googleTag='true';s.src='https://www.googletagmanager.com/gtag/js?id='+encodeURIComponent(id);document.head.appendChild(s);gtag('js',new Date());if(AGGLINK_TRACKING.ga4MeasurementId)gtag('config',AGGLINK_TRACKING.ga4MeasurementId);if(AGGLINK_TRACKING.googleAdsId)gtag('config',AGGLINK_TRACKING.googleAdsId)}
function updateConsent(value){const granted=value==='accepted';gtag('consent','update',{ad_storage:granted?'granted':'denied',analytics_storage:granted?'granted':'denied',ad_user_data:granted?'granted':'denied',ad_personalization:granted?'granted':'denied'});localStorage.setItem(consentKey,value);document.querySelector('.cookie-banner')?.classList.remove('is-visible');if(granted)loadGoogle()}
function banner(){const el=document.createElement('aside');el.className='cookie-banner';el.setAttribute('aria-label','Cookie choices');el.innerHTML='<div class="cookie-inner"><div><strong>Cookie choices</strong><div>We use optional analytics and advertising cookies only with your permission. <a href="/privacy/">Read our privacy and cookies notice</a>.</div></div><div class="cookie-actions"><button type="button" data-consent="rejected">Reject optional cookies</button><button type="button" class="accept" data-consent="accepted">Accept optional cookies</button></div></div>';document.body.appendChild(el);el.querySelectorAll('[data-consent]').forEach(b=>b.addEventListener('click',()=>updateConsent(b.dataset.consent)));if(!localStorage.getItem(consentKey))el.classList.add('is-visible')}
document.addEventListener('DOMContentLoaded',()=>{banner();if(localStorage.getItem(consentKey)==='accepted')updateConsent('accepted');document.querySelectorAll('a[href^="tel:"]').forEach(a=>a.addEventListener('click',()=>{gtag('event','phone_click');if(AGGLINK_TRACKING.googleAdsId&&AGGLINK_TRACKING.phoneConversionLabel)gtag('event','conversion',{send_to:AGGLINK_TRACKING.googleAdsId+'/'+AGGLINK_TRACKING.phoneConversionLabel})}));document.querySelectorAll('a[href^="mailto:"]').forEach(a=>a.addEventListener('click',()=>gtag('event','email_click')))});
window.addEventListener('agglink:lead',e=>{gtag('event','generate_lead',{form_name:e.detail.form});if(AGGLINK_TRACKING.googleAdsId&&AGGLINK_TRACKING.quoteConversionLabel)gtag('event','conversion',{send_to:AGGLINK_TRACKING.googleAdsId+'/'+AGGLINK_TRACKING.quoteConversionLabel})});